Стилизация главной страницы
htmlacademy-htmlcss/1707573-sedona-30 pull request #5
Opened 2021-02-01 21:09 UTC by alxshbln

2021-02-03 11:21 UTC, sergeiwerty requested changes
Хорошая работа. 
Каких-то серьёзных проблем нет. Многое из того, на что я сейчас обратил внимание, ты скорее всего и сам бы увидел далее, но тем не менее моя роль в том, чтобы указывать на подобные вещи.

2021-02-03 11:21 UTC, sergeiwerty commented on css/style.css
> +  font-weight: 700;
Кстати, на главной вроде всё же чаще задействован font-weight: 700 - это тоже было оптимальнее использовать для подобных элементов

2021-02-03 11:21 UTC, sergeiwerty commented on index.html
>        <div class="header-logo">
Но ведь это скорее баннер, чем логотип. Логотипом можно назвать то, что сейчас значится под классом .main-header-logo. Возникает некоторая путаница.

2021-02-03 11:21 UTC, sergeiwerty commented on css/style.css
> +.appointment {
У текста из appointment-info значение line-height должно быть 24px

2021-02-03 11:21 UTC, sergeiwerty commented on css/style.css
> +.appointment .heading {
Здесь также значение line-height должно быть 24px

2021-02-05 09:49 UTC, alxshbln commented on css/style.css
> +.appointment .heading {
А тут мне бы хотелось понять как поступать лучше: font-size задан 30px, a line-height: 24px. Как правильнее, писать один в один из макета, или ставить универсально line-height: 1.2; ? Пока поставил как в макете

2021-02-06 10:59 UTC, sergeiwerty commented on css/style.css
> +.appointment .heading {
В этом случае, т.к. вёрстка делается по макету и все размеры берутся оттуда соответсвенно (в данном контексте речь в первую очередь о font-size), то логично брать вообще все размеры оттуда. Т.к. здесь font-size фиксированно задан в px, то задание line-height в виде числа-коэффициента  (1.2 или другое) не будет иметь смысла.

2021-02-06 11:02 UTC, merged